✨ Initiate Implementation Guide
ncpi-fhir/ncpi-fhir-ig pull request #5
Opened 2021-02-19 08:16 UTC by liberaliscomputing

This PR initiates Implementation Guide development by:

- Setting up the directory structure, including basic configurations;
- Migrating skeleton resources; and
- Providing a quick start instruction

This PR also closes #2.

2021-02-22 16:13 UTC, torstees reviewed
It's probably worth adding a note that the yaml configuration is not valid for pre 1.x releases of sushi in the readme.

2021-02-22 22:41 UTC, bwalsh requested changes

2021-02-23 18:09 UTC, bwalsh approved these changes

2021-02-23 18:11 UTC, torstees approved these changes
Looks like a good starting point.

2021-02-23 18:24 UTC, merged